repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: poetry run ruff --fix
        language: system
        types: [python]
        files: "^src/.+|^tests/.+|noxfile.py"
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
        files: "^src/.+|^tests/.+|noxfile.py"
      - id: darglint
        name: darglint
        entry: poetry run darglint -v 2
        language: system
        types: [python]
        files: "^src/.+|^tests/.+|noxfile.py"
      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types: [python]
        files: "^src/.+|^tests/.+|noxfile.py"
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.0
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
